//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""Members"" : {""CanAdd"" : #CanAddMembers#,""CanView"" : #CanViewMembers#,""CanEdit"" : #CanEditMembers#,""CanDelete"" : #CanDeleteMembers#},
 ""Coaches"" : {""CanAdd"" : #CanAddCoaches#, ""CanView"" : #CanViewCoaches#,""CanEdit"" : #CanEditCoaches#,""CanDelete"" : #CanDeleteCoaches#},
 ""Moderators"" : {""CanAdd"" : #CanAddModerators#,""CanView"" : #CanViewModerators#,""CanEdit"" : #CanEditModerators#,""CanDelete"" : #CanDeleteModerators#},
 ""Admins"" : {""CanAdd"" : #CanAddAdmins#,""CanView"" : #CanViewAdmins#,""CanEdit"" : #CanEditAdmins#,""CanDelete"" : #CanDeleteAdmins#""IsSuper"" : #IsSuperAdmin#}, 
 ""Forms"" : {
	""Attendance"" : {""ViewCoaches"" : #ViewCoachesAttendance#,""ViewModerators"" : #ViewModeratorsAttendance#,""ViewAdmins"" : #ViewAdminsAttendance#},
	""Ads"" : {""CanAdd"" : #CanAddAds#,""CanEdit"" : #CanEditAds#,""CanView"" : #CanViewAds#,""CanDelete"" : #CanDeleteAds#},
	""Permissions"" : {""CanAdd"" : #CanAddPermissions#,""CanEdit"" : #CanEditPermissions#,""CanView"" : #CanViewPermissions#,""CanDelete"" : #CanDeletePermissions#},
	""ViewForms"" : {""ViewAttendance"" : #ViewAttendanceForm#,""ViewAds"" : #ViewAdsForm#,""ViewPermissions"" : #ViewPermissionsForm#}
}}
")]
        public string PermissionText {
            get {
                return ((string)(this["PermissionText"]));
            }
        }
    }
}
